language: node_js
node_js:
    - 12
    - 14

branches:
    only:
        - master

before_install:
    - npm install -g yarn

script:
    - yarn test

notifications:
    email:
        - mrvisser@gmail.com
